name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CC: gcc
  CXX: g++

jobs:
  build_and_test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            lcov \
            build-essential \
            git

      - name: Build and install GTest/GMock
        run: |
          # Установка из системных пакетов (достаточно для Ubuntu 24.04)
          sudo apt-get install -y libgtest-dev libgmock-dev

          # Сборка и установка GTest
          cd /usr/src/googletest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/libgtest.a lib/libgtest_main.a /usr/lib

          # Сборка и установка GMock
          cd /usr/src/googletest/googlemock
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/libgmock.a lib/libgmock_main.a /usr/lib

      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake .. -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build project
        run: |
          cd build
          cmake --build . --config Debug

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate coverage report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/test/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage
          retention-days: 5
