1s
Run set -x
  set -x
  cd /home/runner/work/lab05dz/lab05dz/build
  lcov -directory . -directory test -capture -output-file coverage.info
  lcov -remove coverage.info '/usr/*' '*/test/*' -output-file coverage.info
  genhtml -output-directory coverage coverage.info
  set +x
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
+ cd /home/runner/work/lab05dz/lab05dz/build
+ lcov -directory . -directory test -capture -output-file coverage.info
Capturing coverage data from . test
geninfo cmd: '/usr/bin/geninfo . test --output-filename coverage.info --memory 0'
Found gcov version: 13.3.0
geninfo: ERROR: cannot read test!
	(use "geninfo --ignore-errors gcov ..." to bypass this error)
Using intermediate gcov format
Error: Process completed with exit code 9.
