name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Re-enable Windows
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set Git Path (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Adding Git to PATH"
          $env:PATH = "C:\Program Files\Git\bin;" + $env:PATH
          Write-Host "PATH: $($env:PATH)"

      - name: Reset network settings (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Resetting network settings"
          netsh winsock reset
          netsh int ip reset
          ipconfig /flushdns

      - uses: actions/checkout@v3
        with:
          #sparse-checkout-cone-mode: false # Removed
          #fetch-depth: 1 # Removed
          lfs: false # or true, depending on your repo
          submodules: recursive # Add this line

      - name: Install cmake (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash
        timeout-minutes: 5  # Increased timeout
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install gtest (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash
        timeout-minutes: 5  # Increased timeout
        run: sudo apt-get install -y libgtest-dev

      - name: Remove build directory (Clean CMake Cache) - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: rm -rf ${{ github.workspace }}/build && rm -f ${{ github.workspace }}/CMakeCache.txt

      - name: Remove build directory (Clean CMake Cache) - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: Remove-Item -Path ${{ github.workspace }}/build -Recurse -Force

      - name: Clear Git Cache
        shell: bash
        run: git fetch --all --prune

      - name: Debug - List Files
        shell: bash
        run: |
          echo "Listing files in ${{ github.workspace }}"
          ls -lR ${{ github.workspace }}

      - name: Debug - Environment Variables - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "Environment variables:"
          env

      - name: Debug - Environment Variables - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "Environment variables:"
          Get-ChildItem Env:

      - name: Configure CMake - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          SOURCE_DIR="${{ github.workspace }}"  # Corrected path! CMakeLists.txt in root
          BUILD_DIR="${{ github.workspace }}/build"
          echo "Source directory: $SOURCE_DIR"
          echo "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release
          set +x

      - name: Configure CMake - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $SOURCE_DIR = "${{ github.workspace }}"  # Corrected path! CMakeLists.txt in root
          $BUILD_DIR = "${{ github.workspace }}/build"
          Write-Host "Source directory: $SOURCE_DIR"
          Write-Host "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release

      - name: Build - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          BUILD_DIR="${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release
          set +x

      - name: Build - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $BUILD_DIR = "${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release
