name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set Git Path (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Adding Git to PATH"
          $env:PATH = "C:\Program Files\Git\bin;" + $env:PATH
          Write-Host "PATH: $($env:PATH)"

      - name: Reset network settings (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Resetting network settings"
          netsh winsock reset
          netsh int ip reset
          ipconfig /flushdns

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        shell: bash
        timeout-minutes: 5
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgtest-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Install Chocolatey (Package Manager for Windows)
          choco install -y cmake.install
		  # Install NuGet CLI
          choco install nuget.commandline -y

          # Add NuGet to PATH
          $env:PATH = "$($env:PATH);C:\ProgramData\chocolatey\lib\nuget.commandline\tools"
          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "User")

          # Install GTest using NuGet
          nuget install googletest -Version 1.14.0 -OutputDirectory lib

          # Set environment variable for GTest
          [Environment]::SetEnvironmentVariable("GTEST_ROOT", "${{ github.workspace }}\lib\googletest.1.14.0\build\native\include", "User")
          # Add CMake to PATH
          $env:PATH = "C:\Program Files\CMake\bin;" + $env:PATH
          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, "User")
          Write-Host "GTEST_ROOT environment variable set"
          Write-Host "CMake added to PATH"

      - name: Remove build directory (Clean CMake Cache) - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: rm -rf ${{ github.workspace }}/build && rm -f ${{ github.workspace }}/CMakeCache.txt

      - name: Remove build directory (Clean CMake Cache) - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $BUILD_DIR = "${{ github.workspace }}/build"
          if (Test-Path -Path $BUILD_DIR) {
            Remove-Item -Path $BUILD_DIR -Recurse -Force -ErrorAction SilentlyContinue
          } else {
            Write-Host "Build directory does not exist, skipping removal."
          }

      - name: Clear Git Cache
        shell: bash
        run: git fetch --all --prune

      - name: Debug - List Files - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "Listing files in ${{ github.workspace }}"
          ls -lR ${{ github.workspace }}

      - name: Debug - List Files - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Listing files in ${{ github.workspace }}"
          Get-ChildItem -Path ${{ github.workspace }} -Recurse | Format-List

      - name: Debug - Environment Variables - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          echo "Environment variables:"
          env

      - name: Debug - Environment Variables - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "Environment variables:"
          Get-ChildItem Env:

      - name: Configure CMake - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          SOURCE_DIR="${{ github.workspace }}"
          BUILD_DIR="${{ github.workspace }}/build"
          echo "Source directory: $SOURCE_DIR"
          echo "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release
          set +x

      - name: Configure CMake - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $SOURCE_DIR = "${{ github.workspace }}"
          $BUILD_DIR = "${{ github.workspace }}/build"
          Write-Host "Source directory: $SOURCE_DIR"
          Write-Host "Build directory: $BUILD_DIR"
          cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release

      - name: Build - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          BUILD_DIR="${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release
          set +x

      - name: Build - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $BUILD_DIR = "${{ github.workspace }}/build"
          cmake --build "$BUILD_DIR" --config Release

      - name: Test - Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          BUILD_DIR="${{ github.workspace }}/build"
          ctest --test-dir "$BUILD_DIR"
          set +x

      - name: Test - Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $BUILD_DIR = "${{ github.workspace }}/build"
          ctest --test-dir "$BUILD_DIR"
